apiVersion: v2
name: ollama
description: A Helm chart for an easier ollama (https://ollama.com) deployment on k8s. Please note that this is a private helm chart and not directly or indirectly affiliated with ollama or its authors.
type: application
# renovate: bumpVersion
version: "0.20.1"
# renovate: image=ollama/ollama
appVersion: "0.18.1"
home: https://github.com/CodeAdminDe/helm-charts
keywords:
  - ollama
  - ai
  - ki
  - llm
  - backend
  - helm
  - cloud-native
maintainers:
  - name: Frederic Roggon
    email: frederic.roggon@codeadmin.de
    url: https://github.com/CodeAdminDe
dependencies:
- name: libchart-cnps
  version: 0.2.1
  repository: https://codeadminde.github.io/helm-charts
  alias: libchart-cnps
  condition: libchartCnps.deployAndYesIUnderstandAndAccceptTheRisk
