apiVersion: v2
name: headscale
description: A Helm chart for an easier headscale (https://headscale.net) deployment on Kubernetes. Please note that this is a private helm chart and not directly or indirectly affiliated with headscale or its authors.
type: application
# renovate: bumpVersion
version: 0.2.0
# renovate: image=headscale/headscale
appVersion: "0.28.0"
home: https://github.com/CodeAdminDe/helm-charts
keywords:
  - headscale
  - tailscale
  - vpn
  - mesh-network
  - networking
  - cloud-native
  - helm
maintainers:
  - name: Frederic Roggon
    email: frederic.roggon@codeadmin.de
    url: https://github.com/CodeAdminDe
dependencies:
  - name: libchart-cnps
    version: 0.2.1
    repository: https://codeadminde.github.io/helm-charts
    alias: libchart-cnps
    condition: libchartCnps.enabled
annotations:
  category: Networking
  kubeVersion: ">=1.24.0"
  securityContext: "required"
  images: |
    - name: headscale
      image: headscale/headscale:0.28.0
    - name: headscale-ui
      image: ghcr.io/gurucomputing/headscale-ui:2026.03.17
    - name: headplane
      image: ghcr.io/tale/headplane:0.6.2
